spring:
  application:
    name: matzip
  profiles:
    active: private
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
          connectiontimeout: 5000
server:
  port: 8080

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: VARCHAR
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
<<<<<<< HEAD
  type-aliases-package: com.kh.matzip.member.model.vo, com.kh.matzip.member.model.dto,com.kh.matzip.mypage.model.dto, com.kh.matzip.store.model.dto, com.kh.matzip.reservation.model.vo, com.kh.matzip.reservation.model.dto
=======
  type-aliases-package: com.kh.matzip.member.model.vo, com.kh.matzip.member.model.dto,com.kh.matzip.mypage.model.dto, com.kh.matzip.store.model.dto, com.kh.matzip.notice.model.dto
  
>>>>>>> 2286a98259e30380aaed52c7c439f227e1b66df3
